name: Build QMK firmware

on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    name: 'QMK Userspace Build'
    uses: qmk/.github/.github/workflows/qmk_userspace_build.yml@main
    with:
      qmk_repo: qmk/qmk_firmware
      qmk_ref: master
      preparation_command: >-
        for kb in keyboards/*/keyboard.json; do
          kb_name=$(basename $(dirname "$kb"));
          if [ ! -d "qmk_firmware/keyboards/$kb_name" ]; then
            ln -s "$GITHUB_WORKSPACE/keyboards/$kb_name" "qmk_firmware/keyboards/$kb_name";
          fi;
        done

  publish:
    name: 'QMK Userspace Publish'
    uses: qmk/.github/.github/workflows/qmk_userspace_publish.yml@main
    if: always() && !cancelled()
    needs: build
